env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - react
  - import
rules: {
# "no-console": ["error", { allow: ["warn", "error"] }],
"no-unused-expressions": "error",
"curly": "error",
"react/jsx-uses-react": 0,
"react/react-in-jsx-scope": 0,
# "import/prefer-default-export": "off",
"import/order": [
  "error",
  {
    "groups": [
        "builtin",
          "external",
          "internal",
          "parent",
          "sibling",
          "index",
          "object",
          "type"
    ]
  }
]
}
